version: '3'
services:

  postgres:
    volumes:
      - "postgres-data:/data/postgres"
    env_file:
      - docker-compose.prod.postgres.env

  bot:
    env_file:
      - docker-compose.prod.bot.env

volumes:
  postgres-data: