version: '3'
services:

  postgres:
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data-dev:/data/postgres"
    env_file:
      - docker-compose.dev.postgres.env

  redis:
    ports:
      - "6379:6379"

  bot:
    ports:
      - "3000:80"
    volumes:
      - ".:/usr/src"
    env_file:
      - docker-compose.dev.bot.env
    command: npm run dev

volumes:
  postgres-data-dev: